// lib/upload-queue.ts
//
// Persistent pending-upload queue (Task 9.1, design Component 5).
//
// Stores upload *intent + metadata* — NEVER file bytes — in IndexedDB so that
// interrupted uploads can be surfaced to the user after a crash, refresh, or
// browser restart (design D4, Requirements 6.1-6.5, 11.4, 18.2). This module is
// PURE PERSISTENCE: it reads and writes records. It does NOT perform uploads,
// does NOT call the confirm endpoint, and does NOT talk to any store. The
// orchestration/recovery flows that consume these records live in the upload
// store (Task 9.2+) and are intentionally out of scope here.
//
// CLIENT-SAFETY / SSR / BUILD SAFETY:
//   - No browser API (`indexedDB`, `window`, ...) is touched at MODULE
//     EVALUATION time. Every access is lazy, inside a function, and guarded by a
//     `typeof indexedDB !== 'undefined'` check, so this module is safe to import
//     in a Next.js server/build context without throwing.
//   - This module declares no `"use server"` and imports nothing server-only.
//   - It references NO server env and never `BLOB_READ_WRITE_TOKEN`; it persists
//     only the metadata fields listed in `QueueRecord` (Req 6.2).
//
// GRACEFUL DEGRADATION (Req 11.6 — the crux of this module):
//   IndexedDB is NOT guaranteed to be available (private-mode quirks, disabled
//   storage, SSR/build, blocked upgrades, transaction errors). A persistence
//   failure must NEVER turn a valid upload into a failed upload. Therefore
//   EVERY exported operation degrades gracefully:
//     - `put` / `patch` / `remove` swallow environmental failures internally
//       (at most a single non-secret `console.warn`) and RESOLVE (never reject).
//     - `all` resolves to `[]` when IndexedDB is unavailable or any read fails.
//   This is the correct reading of "must not reject": the persistence API
//   no-ops and resolves on environmental failure so callers are never broken.
//
// IDEMPOTENCY:
//   One `uploadId` = one logical upload = ultimately one media row. The object
//   store is keyed by `uploadId` (its primary key / keyPath). This module never
//   creates or regenerates an `uploadId` — callers pass it in and it is used
//   as-is for `put`/`patch`/`remove`. Nothing here can produce a new id on
//   recovery or refresh (design D3, Req 7.1/7.2/13.2).

/**
 * Lifecycle status of a persisted upload record. This is the design's exact
 * `QueueStatus` union (design Component 5) and is the source of truth consumed
 * by the upload store in Task 9.2. Terminology note: `queued` here corresponds
 * to the store's "pending"-style initial state; there is deliberately no
 * `cancelled` status in the persisted queue — cancellation is application
 * behavior owned by the store (Task 9.2), not persistence.
 */
export type QueueStatus =
    | 'queued'
    | 'processing'
    | 'uploading'
    | 'completed'
    | 'failed';

/**
 * A single persisted pending-upload record. Exactly the design's `QueueRecord`
 * shape (design Component 5, Req 6.4). Metadata + intent only — no file bytes.
 */
export interface QueueRecord {
    /** Primary key / correlation id (UUID v4). Never regenerated by this module. */
    uploadId: string;
    /** Event the upload targets (route context for recovery). */
    eventSlug: string;
    /** Original filename (display + confirm body reconstruction). */
    filename: string;
    /** MIME of the bytes intended for upload (validation + confirm). */
    contentType: string;
    /** Original file size in bytes. */
    originalSize: number;
    /** Size of the processed bytes; null until preprocessing is known. */
    processedSize: number | null;
    /** Current lifecycle status; drives recovery branch selection in Task 9.2. */
    status: QueueStatus;
    /** Public Blob URL once `upload()` resolves; null before that. */
    blobUrl: string | null;
    /**
     * Client-computed BlurHash for the image, or null (Change 2/3). Persisted so
     * confirm-only recovery and auto-resume after a reload can send the SAME
     * BlurHash the same-session confirm would have sent, instead of losing it.
     * Optional/back-compat: legacy records without it behave as blurhash-less.
     */
    blurhash?: string | null;
    /** Last error message on failure; null otherwise (Req 18.2). */
    error: string | null;
    /**
     * ISO-8601 enqueue-time upload-intent timestamp (Req 6.4/6.6). Captured
     * ONCE at enqueue and NEVER modified on later state transitions. This is the
     * same value the same-session confirm path sends to the Confirm_Endpoint,
     * and it is reused by confirm-only recovery as the media `date` after a
     * reload — so it is DISTINCT from `updatedAt` (the last-updated timestamp).
     * `put`/`patch` structurally preserve it (see below) so it can never be
     * overwritten by an updatedAt/retry/processing/upload/recovery time.
     */
    date: string;
    /** Last-updated timestamp (ms since epoch); managed by this module. */
    updatedAt: number;

    // --- Optional recovery-UX metadata (Change 3, byte-persisted auto-resume) --
    // All OPTIONAL and back-compat: legacy records written before Change 3 lack
    // them and behave exactly as before (treated as "no bytes, no thumbnail").
    // Bytes themselves are NEVER stored on this metadata record — only in the
    // separate `upload-bytes` object store (see putBytes/getBytes) so `all()`
    // stays cheap and the metadata store stays clean.

    /** 'image' | 'video' classification captured at enqueue (recovery branch). */
    kind?: 'image' | 'video';
    /**
     * True when the actual upload bytes were persisted in the `upload-bytes`
     * store (resumable images <= cap). Drives transparent auto-resume on reload.
     */
    hasBytes?: boolean;
    /** True for an image over the resumable size cap (bytes NOT persisted). */
    oversized?: boolean;
    /**
     * Small downscaled preview data URL persisted for records whose bytes are
     * NOT stored (videos, oversized images) so recovery can show a thumbnail
     * plus a dismissable warning instead of a blank placeholder. Null/absent
     * otherwise.
     */
    thumbnailDataUrl?: string | null;
}

// --- IndexedDB configuration (single database, single object store) -----------

const DB_NAME = 'golden-core-uploads';
// Bumped to 2 to add the separate `upload-bytes` object store (Change 3). The
// upgrade is additive — it only creates the new store if missing, so existing
// `uploads` records survive the upgrade untouched.
const DB_VERSION = 2;
const STORE_NAME = 'uploads';
// Separate object store holding the actual upload bytes for resumable images
// (Change 3). Keyed by uploadId; value is { uploadId, blob }. Kept OUT of the
// metadata store so `all()` never loads bytes and the metadata store stays a
// pure, cheap intent/metadata log.
const BYTES_STORE_NAME = 'upload-bytes';
const KEY_PATH: keyof QueueRecord = 'uploadId';

/**
 * Cached open-database promise so repeated operations reuse one connection.
 * Resolves to `null` whenever IndexedDB is unavailable or the open fails/blocks;
 * a `null` result is treated as "persistence disabled" by every operation.
 *
 * We cache the PROMISE (not the resolved db) so concurrent callers share a
 * single in-flight open. We only re-attempt after a settled failure (`null`) by
 * clearing the cache, so a transient environment can recover on a later call.
 */
let dbPromise: Promise<IDBDatabase | null> | null = null;

/** Non-secret warning helper. Logs metadata only — never record contents. */
function warn(message: string): void {
    // A single, non-secret breadcrumb. Never logs file bytes, tokens, or record
    // values — only a short description of the degraded persistence path.
    console.warn(`[upload-queue] ${message}`);
}

/** True only when the native IndexedDB API is present in this environment. */
function isIndexedDbAvailable(): boolean {
    return typeof indexedDB !== 'undefined';
}

/**
 * Lazily open (and cache) the IndexedDB connection. Returns `null` — never
 * throws/rejects — when IndexedDB is unavailable or the open fails/blocks.
 * Creates the single object store keyed by `uploadId` in `onupgradeneeded`.
 */
function openDb(): Promise<IDBDatabase | null> {
    // Guard at call time (never at module top-level) so SSR/build never touches
    // a browser-only global.
    if (!isIndexedDbAvailable()) {
        return Promise.resolve(null);
    }

    if (dbPromise) {
        return dbPromise;
    }

    dbPromise = new Promise<IDBDatabase | null>((resolve) => {
        // Settle-once guard + safety timeout. An IndexedDB open can, in rare
        // environments, neither succeed nor error nor fire `blocked` promptly
        // (e.g. a version upgrade blocked by a connection in another tab that
        // never closes). Persistence is best-effort, so if the open has not
        // settled shortly we resolve `null` (persistence disabled) so callers are
        // NEVER left awaiting forever — this is the difference between "no
        // cross-reload resume" and "uploads hang at 0%".
        let settled = false;
        const settle = (db: IDBDatabase | null) => {
            if (settled) return;
            settled = true;
            resolve(db);
        };
        const timer =
            typeof setTimeout === 'function'
                ? setTimeout(() => {
                      warn('open timed out; persistence disabled');
                      settle(null);
                  }, 3000)
                : null;
        const clear = () => {
            if (timer && typeof clearTimeout === 'function') clearTimeout(timer);
        };

        let request: IDBOpenDBRequest;
        try {
            request = indexedDB.open(DB_NAME, DB_VERSION);
        } catch {
            // Some environments throw synchronously on open (e.g. storage
            // disabled). Treat as unavailable.
            warn('open threw synchronously; persistence disabled');
            clear();
            settle(null);
            return;
        }

        request.onupgradeneeded = () => {
            const db = request.result;
            if (!db.objectStoreNames.contains(STORE_NAME)) {
                // Metadata object store keyed by uploadId (design: "single object
                // store keyed by uploadId"). No extra indexes: all() uses
                // getAll() and every other op is a primary-key lookup, so no
                // secondary index is justified.
                db.createObjectStore(STORE_NAME, { keyPath: KEY_PATH });
            }
            if (!db.objectStoreNames.contains(BYTES_STORE_NAME)) {
                // Separate bytes store (Change 3). Value shape { uploadId, blob }
                // keyed by uploadId so byte persistence never bloats the metadata
                // store and all() stays cheap. Created additively on the v1->v2
                // upgrade without touching existing metadata records.
                db.createObjectStore(BYTES_STORE_NAME, { keyPath: KEY_PATH });
            }
        };

        request.onsuccess = () => {
            clear();
            const db = request.result;
            // If a LATER version upgrade is requested (e.g. another tab bumps the
            // schema), close this connection so we don't block that tab's upgrade
            // — and drop the cache so the next call re-opens at the new version.
            db.onversionchange = () => {
                try {
                    db.close();
                } catch {
                    /* ignore */
                }
                dbPromise = null;
            };
            // If the connection is closed unexpectedly (the DB was deleted via
            // devtools/"clear site data", storage was reclaimed, or the tab was
            // frozen), DROP the cached promise so the NEXT operation re-opens
            // (and re-creates the object stores). Without this, a stale CLOSED
            // handle stays cached and every later transaction throws
            // InvalidStateError -> silent no-op -> nothing is persisted -> a
            // refresh has nothing to resume.
            db.onclose = () => {
                if (dbPromise) dbPromise = null;
            };
            settle(db);
        };

        request.onerror = () => {
            warn('open failed; persistence disabled');
            clear();
            settle(null);
        };

        request.onblocked = () => {
            // Another connection is blocking the upgrade. Do not hang the
            // caller: treat as unavailable so the upload still proceeds.
            warn('open blocked; persistence disabled');
            clear();
            settle(null);
        };
    });

    // If the open settled as unavailable, clear the cache so a later call can
    // retry in a possibly-recovered environment.
    void dbPromise.then((db) => {
        if (db === null) {
            dbPromise = null;
        }
    });

    return dbPromise;
}

/**
 * Run `work` inside a transaction on the uploads store and resolve with its
 * result. Any environmental failure (no IndexedDB, transaction/abort/error, or
 * thrown exception) resolves to `fallback` instead of rejecting, so a
 * persistence failure can never fail a valid upload (Req 11.6).
 */
/**
 * Attempt one transaction against `db`. Resolves `{ ok: true, value }` on
 * success, `{ ok: false }` when the transaction could not even be set up (a
 * strong signal the connection is closed/stale — the caller may re-open and
 * retry), or resolves `{ ok: true, value: fallback }` when the request errored
 * (a real request error, not a dead connection).
 */
function runOnce<T>(
    db: IDBDatabase,
    mode: IDBTransactionMode,
    fallback: T,
    work: (store: IDBObjectStore) => IDBRequest,
    storeName: string,
): Promise<{ ok: boolean; value: T }> {
    // A legacy/partial DB may not contain the store (e.g. upgrade could not
    // run). Treat as "unavailable for this store" — no-op resolve.
    if (!db.objectStoreNames.contains(storeName)) {
        return Promise.resolve({ ok: true, value: fallback });
    }
    return new Promise((resolve) => {
        let request: IDBRequest;
        try {
            const tx = db.transaction(storeName, mode);
            const store = tx.objectStore(storeName);
            request = work(store);
        } catch {
            // transaction() throws InvalidStateError when the connection is
            // closing/closed (DB deleted, storage reclaimed). Signal "not ok" so
            // the caller can drop the cache and re-open once.
            resolve({ ok: false, value: fallback });
            return;
        }
        request.onsuccess = () => resolve({ ok: true, value: request.result as T });
        request.onerror = () => {
            warn('request failed; operation no-op');
            resolve({ ok: true, value: fallback });
        };
    });
}

/**
 * Run `work` inside a transaction on the given store and resolve with its
 * result. Any environmental failure (no IndexedDB, transaction/abort/error, or
 * thrown exception) resolves to `fallback` instead of rejecting, so a
 * persistence failure can never fail a valid upload (Req 11.6).
 *
 * RESILIENCE (ensure IndexedDB is "always there" across refreshes and deletes):
 * if the cached connection is closed/stale (transaction setup throws), DROP the
 * cached promise and RE-OPEN once — `indexedDB.open` transparently re-creates a
 * deleted database and its object stores via `onupgradeneeded`. This means that
 * after the DB is cleared (devtools / "clear site data") or a connection is
 * silently closed, the very next queue operation recreates the store instead of
 * no-op'ing forever.
 */
async function withStore<T>(
    mode: IDBTransactionMode,
    fallback: T,
    work: (store: IDBObjectStore) => IDBRequest,
    storeName: string = STORE_NAME,
): Promise<T> {
    const db = await openDb();
    if (!db) {
        return fallback;
    }

    const first = await runOnce(db, mode, fallback, work, storeName);
    if (first.ok) {
        return first.value;
    }

    // The cached connection was closed/stale. Drop it and re-open (recreating
    // the DB + stores if they were deleted), then retry exactly once.
    dbPromise = null;
    const fresh = await openDb();
    if (!fresh) {
        return fallback;
    }
    const second = await runOnce(fresh, mode, fallback, work, storeName);
    return second.value;
}

/**
 * Persistent upload-queue API. Every method degrades gracefully: writes no-op
 * and resolve on failure; `all()` resolves to `[]`. See the module header.
 */
export const uploadQueue: {
    put(rec: QueueRecord): Promise<void>;
    patch(uploadId: string, partial: Partial<QueueRecord>): Promise<void>;
    remove(uploadId: string): Promise<void>;
    all(): Promise<QueueRecord[]>;
    putBytes(uploadId: string, blob: Blob): Promise<void>;
    getBytes(uploadId: string): Promise<Blob | null>;
    removeBytes(uploadId: string): Promise<void>;
} = {
    /**
     * Upsert a full record by its `uploadId` key. Refreshes `updatedAt` to
     * `Date.now()` so callers get a consistent timestamp. Never stores bytes
     * (the caller only ever passes `QueueRecord` metadata). Resolves even when
     * persistence is unavailable.
     */
    async put(rec: QueueRecord): Promise<void> {
        const record: QueueRecord = { ...rec, updatedAt: Date.now() };
        await withStore('readwrite', undefined, (store) => store.put(record));
    },

    /**
     * Read-modify-write a subset of fields for an existing record within one
     * transaction. Refreshes `updatedAt`. The `uploadId` key is never changed
     * (any `uploadId` present in `partial` is overridden back to the target),
     * and the enqueue-time `date` is likewise forced back to the record's
     * original value so it is immutable after creation (Req 6.6).
     * If no record exists for `uploadId`, this is a no-op resolve (there is
     * nothing to patch; creating a partial record could persist an incomplete,
     * un-typed row). Resolves even when persistence is unavailable.
     */
    async patch(
        uploadId: string,
        partial: Partial<QueueRecord>,
    ): Promise<void> {
        // Attempt the read-modify-write against a connection. Resolves `false`
        // ONLY when the connection is closed/stale (transaction setup threw), so
        // the caller can re-open and retry once (same resilience as withStore).
        const attempt = (db: IDBDatabase): Promise<boolean> =>
            new Promise<boolean>((resolve) => {
                if (!db.objectStoreNames.contains(STORE_NAME)) {
                    resolve(true); // store missing -> treat as no-op success
                    return;
                }
                let store: IDBObjectStore;
                try {
                    const tx = db.transaction(STORE_NAME, 'readwrite');
                    store = tx.objectStore(STORE_NAME);
                } catch {
                    resolve(false); // closed/stale connection -> signal retry
                    return;
                }

                const getReq = store.get(uploadId);
                getReq.onerror = () => {
                    warn('patch read failed; no-op');
                    resolve(true);
                };
                getReq.onsuccess = () => {
                    const existing = getReq.result as QueueRecord | undefined;
                    if (!existing) {
                        // Nothing to patch — no-op resolve (documented choice).
                        resolve(true);
                        return;
                    }
                    const merged: QueueRecord = {
                        ...existing,
                        ...partial,
                        // Preserve the key: uploadId is never regenerated.
                        uploadId: existing.uploadId,
                        // Structurally immutable enqueue-time date (Req 6.6).
                        date: existing.date,
                        updatedAt: Date.now(),
                    };
                    let putReq: IDBRequest;
                    try {
                        putReq = store.put(merged);
                    } catch {
                        warn('patch write setup failed; no-op');
                        resolve(true);
                        return;
                    }
                    putReq.onsuccess = () => resolve(true);
                    putReq.onerror = () => {
                        warn('patch write failed; no-op');
                        resolve(true);
                    };
                };
            });

        const db = await openDb();
        if (!db) return;

        const ok = await attempt(db);
        if (ok) return;

        // Closed/stale connection: drop the cache, re-open (recreating the DB +
        // stores if deleted), and retry exactly once.
        dbPromise = null;
        const fresh = await openDb();
        if (!fresh) return;
        await attempt(fresh);
    },

    /**
     * Delete the metadata record for `uploadId` (used when a media row is
     * confirmed, Req 6.5) AND its persisted bytes, so no orphaned bytes are ever
     * left behind on any terminal outcome (confirm success / cancel / dismiss).
     * Deleting a missing key is a normal successful no-op in IndexedDB. Resolves
     * even when persistence is unavailable.
     */
    async remove(uploadId: string): Promise<void> {
        await withStore('readwrite', undefined, (store) =>
            store.delete(uploadId),
        );
        // Best-effort bytes cleanup in the same call so callers cannot forget it
        // (mandatory cleanup, Change 3). Resolves/no-ops on any failure.
        await withStore(
            'readwrite',
            undefined,
            (store) => store.delete(uploadId),
            BYTES_STORE_NAME,
        );
    },

    /**
     * Return all persisted records so the store can surface interrupted uploads
     * on app start. Resolves to `[]` on any failure/unavailability (Req 11.6).
     */
    async all(): Promise<QueueRecord[]> {
        const result = await withStore<QueueRecord[]>(
            'readonly',
            [],
            (store) => store.getAll(),
        );
        return Array.isArray(result) ? result : [];
    },

    /**
     * Persist the ACTUAL upload bytes for a resumable image (Change 3) in the
     * separate `upload-bytes` store, keyed by `uploadId`. Called ONLY for images
     * within the size cap; videos and oversized images never reach here (the
     * store persists a thumbnail instead). Stored as `{ uploadId, blob }`. Never
     * puts bytes into the metadata store. Best-effort: resolves (no-op) when
     * IndexedDB or the bytes store is unavailable so an upload never fails just
     * because byte persistence could not happen (Req 11.6). Cross-reload resume
     * is simply not offered in that case.
     */
    async putBytes(uploadId: string, blob: Blob): Promise<void> {
        await withStore(
            'readwrite',
            undefined,
            (store) => store.put({ uploadId, blob }),
            BYTES_STORE_NAME,
        );
    },

    /**
     * Read back the persisted bytes for `uploadId` as a Blob, or null when none
     * exist / persistence is unavailable. Used by transparent auto-resume after
     * a reload to reconstruct the upload body without a reselect.
     */
    async getBytes(uploadId: string): Promise<Blob | null> {
        const rec = await withStore<{ uploadId: string; blob: Blob } | undefined>(
            'readonly',
            undefined,
            (store) => store.get(uploadId),
            BYTES_STORE_NAME,
        );
        return rec && rec.blob instanceof Blob ? rec.blob : null;
    },

    /**
     * Delete the persisted bytes for `uploadId` (mandatory cleanup on every
     * terminal outcome — confirm success / cancel / dismiss). Deleting a missing
     * key is a normal no-op. Resolves even when persistence is unavailable.
     * `remove()` also calls this, but it is exposed so callers can clean up bytes
     * explicitly without removing the metadata record.
     */
    async removeBytes(uploadId: string): Promise<void> {
        await withStore(
            'readwrite',
            undefined,
            (store) => store.delete(uploadId),
            BYTES_STORE_NAME,
        );
    },
};
